# Add the necessary lines to this file to execute your solution.

all: createsubdir 

createsubdir: clean	
	ls
	@echo ""
	python myScript.py
	ls
	@echo ""
	python myScript.py
	@echo ""
	@echo "No error flag showing even subdir exists"

clean: 
	@echo ""
	@echo "remove dir subdir"
	rm -rf subdir
