#
# ZX command file generated by vstorm2 on Mon May  5 20:07:23 2014
#
setvar log_file ./work/zx_VSS.log
setvar library_name fast_allcells.cl
setvar output_file_name ./work/VSS
setvar max_error_messages 100
setvar max_resistor_length 800
layout_file /tmp/eps_out_32049.def.gz 
setvar exec_token "/tmp/eps_out_32049.def.gz"
label port VSS 271.3 261.3 metal8
power_pin_supply_tolerance 0 0.3
setvar extraction_mode early
extraction_type all none
extraction_type pattern VSS r_only
hierarchical_path_tracer netinst_table ./work/VSS.netinst
hierarchical_path_tracer cell_table ./work/VSS.cellinst
setvar output_wlt drawn
setvar use_hpt_leqnets_info true
setvar def_merge_supply_shorts false
setvar promote_ports true
setvar max_cpu 1
setvar density_check_method database
