#
# ZX command file generated by vstorm2 on Mon May  5 20:07:46 2014
#
setvar log_file ./work/zx_VDD.log
setvar library_name fast_allcells.cl
setvar output_file_name ./work/VDD
setvar max_error_messages 100
setvar max_resistor_length 800
layout_file /tmp/eps_out_32049.def.gz 
setvar exec_token "/tmp/eps_out_32049.def.gz"
label port VDD 10.5 261.3 metal8
power_pin_supply_tolerance 0.665 1.235
setvar extraction_mode early
extraction_type all none
extraction_type pattern VDD r_only
hierarchical_path_tracer netinst_table ./work/VDD.netinst
hierarchical_path_tracer cell_table ./work/VDD.cellinst
setvar output_wlt drawn
setvar use_hpt_leqnets_info true
setvar def_merge_supply_shorts false
setvar promote_ports true
setvar max_cpu 1
setvar density_check_method database
